language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      bc
      docbook-xsl
      gengetopt
      gperf
      libxml2-dev
      libpng12-dev
      libjansson-dev
      libcunit1-dev
      xml2
      xmlstarlet
      xsltproc
  - sudo pip install cpp-coveralls
  - autoconf
  - autoheader
install:
  - ./configure --enable-tests --enable-coverage
  - make version
  - make
  - sudo make install
script :
  - make --quiet unit
  - make --quiet test
after_success:
  - coveralls --exclude src/unit --gcov-options '\-lp'
