language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-dev libpng12-dev gengetopt gperf docbook-xsl xsltproc
  - autoconf
  - autoheader
install:
  - ./configure
  - make version
  - make
  - make install
script :
  - make test
