language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-dev libpng12-dev gengetopt gperf docbook-xsl xsltproc
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-4.8; fi
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
  - autoconf
  - autoheader
install:
  - ./configure
  - make version
  - make
  - sudo make install
script :
  - make test
