language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      bc gengetopt gperf xml2
      libxml2-dev
      libpng12-dev
      libjansson-dev
      libcunit1-dev
      xsltproc
      docbook-xsl
  - sudo pip install cpp-coveralls
  - autoconf
  - autoheader
install:
  - ./configure --enable-tests
  - make version
  - CFLAGS=--coverage LDFLAGS=--coverage make
  - sudo make install
script :
  - CFLAGS=--coverage LDFLAGS=--coverage make --quiet unit
  - CFLAGS=--coverage LDFLAGS=--coverage make --quiet test
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
