language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      bc
      docbook-xsl
      gengetopt
      gperf
      libxml2-dev
      libpng12-dev
      libjansson-dev
      libcunit1-dev
      xml2
      xmlstarlet
      xsltproc
  - sudo pip install cpp-coveralls
  - autoconf
  - autoheader
install:
  - ./configure --enable-tests --enable-coverage
  - make version
  - make
  - sudo make install
script :
  - make --quiet unit
  - make --quiet test
after_success:
  - coveralls --exclude src/unit --gcov-options '\-lp'

env:
  global:
   - secure: "Q0DE5mVEpInjLSja4vS2B4sX/blXTu3/RgzFORpE787QHAtua73eqobfa6+gl1aF/c3I5UCTRfQVJ9UYOX/RbYirV7ajhjHQ+lK8u0gcEARZRa4mHPamg8+OJ0tRRgsJcKLfemJJxmc9yefdr6PUTHeh73gzT27OOMUw73udzW4="
addons:
  coverity_scan:
    project:
      name: "jjgreen/cptutils"
      description: "Build submitted via Travis CI"
    notification_email: "j.j.green@gmx.co.uk"
    build_command_prepend: "autoconf ; ./configure ; make clean"
    build_command:   "make"
    branch_pattern: "coverity_scan"