language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-dev libpng12-dev gengetopt gperf
  - autoconf
  - autoheader
  - ./configure
  - make version
  - make
install:
  - make install
script :
  - make test