language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-dev libpng12-dev gengetopt gperf \
         docbook-xsl xsltproc libcunit1-dev bc libjansson-dev
  - autoconf
  - autoheader
install:
  - ./configure --enable-tests
  - make version
  - make
  - sudo make install
script :
  - make --quiet unit
  - make --quiet test
